# Generated by Django 3.1.7 on 2021-10-25 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.IntegerField()),
                ('nombre1', models.CharField(blank=True, max_length=12)),
                ('nombre2', models.CharField(max_length=12)),
                ('apellido1', models.CharField(blank=True, max_length=12)),
                ('apellido2', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
                ('identidad', models.IntegerField(unique=True)),
                ('lugar_nacimiento', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.IntegerField(unique=True)),
                ('tipo_moneda', models.CharField(max_length=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('B', 'Bloqueado')], default='A', max_length=1)),
                ('tipo_cuenta', models.CharField(choices=[('A', 'Ahorro'), ('C', 'Cheque')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancos.cliente')),
            ],
        ),
    ]
